// <auto-generated />
using System;
using AiDemoTransport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiDemoTransport.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    [Migration("20260102144354_AddOfferIdToTransport")]
    partial class AddOfferIdToTransport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiDemoTransport.Models.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryLocationDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<string>("PickupLocationDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("OfferId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ScheduleDate");

                    b.HasIndex("Status");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierId = 101,
                            DeliveryLocationDetails = "456 Business Ave, Corporate District, City B - Contact: Jane Smith, Phone: +1-555-0456",
                            OfferId = 0,
                            PickupLocationDetails = "123 Main St, Downtown, City A - Contact: John Doe, Phone: +1-555-0123",
                            PurchaseId = 1001,
                            ScheduleDate = new DateTime(2026, 1, 3, 14, 43, 54, 238, DateTimeKind.Utc).AddTicks(4712),
                            Status = "Scheduled"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
